# This workflow builds and tests a golang project
name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    strategy:
      matrix:
        goversion:
          # The first entry of the matrix should be the
          # version indicated inside the `go.mod`
          - "1.24"
          - "1.25"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.goversion }}"

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          # Here we should use the current go version
          go-version: "1.25"

      - name: Measure Coverage
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          fail_ci_if_error: true
